Handle subscripted generics in query selector
Fixes:

TypeError: Subscripted generics cannot be used with class and instance checks

But requires Python 3.9:
https://peps.python.org/pep-0585/

https://github.com/Textualize/textual/issues/2867