Export the types that _typing.py imports and makes available
Mostly adding this so that it turns this:

$ poetry run mypy --strict binding.py
binding.py:8: error: Module "textual._typing" does not explicitly export attribute "TypeAlias"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)

into this:

$ poetry run mypy --strict binding.py
Success: no issues found in 1 source file